### ISSUE TITLE
解决三星手机拍照获取不到图片的问题

### ISSUE THREAD

**Issue by yjiang2009** [ryanhoo/PhotoCropper#22]
在三星手机上调用系统拍照后会发现获取不到图片，进入裁剪图片后显示无法加载，原因是三星手机拍照完毕后由于切换了横竖屏会销毁Activity，从而丢失数据。解决办法就是在拍照的Activity里加上android:configChanges="orientation|keyboardHidden|screenSize"，测试通过，完美解决。

**Comment by ryanhoo** [comment]
非常感谢，我回家看看。
