### ISSUE TITLE
连续拍照，返回空白。

### ISSUE THREAD

**Issue by DzMonster** [ryanhoo/PhotoCropper#3]
首先先谢谢po主。
然后问题：
拍照第一次可正常获得图片并可以crop
但事不退出应用 再次使用，则会导致无法获得图片。crop时显示一片灰色

**Comment by ryanhoo** [comment]
Maybe this is a little bit late. I threw myself into iOS for months and really didn't have much time for this. Anyway,  I updated this repo and fixed some bugs, please checkout the latest code if you still need it.
