### ISSUE TITLE
4.4.4选择图片出来的不再是相册，而是一个文件选择的东西，然后选择之后就会出问题

### ISSUE THREAD

**Issue by hangox** [ryanhoo/PhotoCropper#4]

**Comment by quqiufeng** [comment]
我也遇到了...  拍照后截取是OK的

**Comment by ryanhoo** [comment]
Maybe this is a little bit late. I threw myself into iOS and really didn't have much time for this. Anyway, It's a bug that Crop from Gallery won't work on devices after Kitkat. I fixed that and please checkout the latest code.

**Comment by hangox** [comment]
I fix that too,I used something special intent ,open a galley , not a
filechooser :) , thanks author

ryan hoo <notifications@github.com>于2015年5月22日周五 下午5:14写道：

**Comment by ryanhoo** [comment]
@hangox I viewed your code and it's good if it fits your needs or your PM is satisfied with that. :smile:  I updated my projects with denpendency support, including gradle & maven. Check it out.
